[buck2][oss] fix windows build unused import: std::process::Stdio
` python test.py --ci --git --buck2=../buck2_artifacts/buck2`

Before:
```
error: unused import: `std::process::Stdio`
  --> app\buck2_execute_local\src\win\process_group.rs:17:5
   |
17 | use std::process::Stdio;
   |     ^^^^^^^^^^^^^^^^^^^
   |
   = note: requested on the command line with `-D unused-imports`
```